// <auto-generated />
using System;
using HeatExchangeCounterflow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeatExchangeCounterflow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222201028_AddCalculationIdToLayerPoint")]
    partial class AddCalculationIdToLayerPoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("HeatExchangeCounterflow.Models.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InputId");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("HeatExchangeCounterflow.Models.CalculationInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AlphaV")
                        .HasColumnType("REAL");

                    b.Property<double>("ApparatusDiameter")
                        .HasColumnType("REAL");

                    b.Property<double>("GasHeatCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("GasVelocity")
                        .HasColumnType("REAL");

                    b.Property<double>("InitialGasTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("InitialMaterialTemp")
                        .HasColumnType("REAL");

                    b.Property<string>("LayerHeightRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaterialFlow")
                        .HasColumnType("REAL");

                    b.Property<double>("MaterialHeatCapacity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CalculationInput");
                });

            modelBuilder.Entity("LayerPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalculationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DeltaTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("GasTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("MaterialTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("RelativeY")
                        .HasColumnType("REAL");

                    b.Property<double>("Theta1")
                        .HasColumnType("REAL");

                    b.Property<double>("Theta2")
                        .HasColumnType("REAL");

                    b.Property<double>("ThetaGas")
                        .HasColumnType("REAL");

                    b.Property<double>("ThetaMaterial")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId");

                    b.ToTable("LayerPoints");
                });

            modelBuilder.Entity("HeatExchangeCounterflow.Models.Calculation", b =>
                {
                    b.HasOne("HeatExchangeCounterflow.Models.CalculationInput", "Input")
                        .WithMany()
                        .HasForeignKey("InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Input");
                });

            modelBuilder.Entity("LayerPoint", b =>
                {
                    b.HasOne("HeatExchangeCounterflow.Models.Calculation", null)
                        .WithMany("Points")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeatExchangeCounterflow.Models.Calculation", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
